spring:
  application:
    name: alunos
  datasource:
    url: jdbc:postgresql://localhost:5432/unittestexample
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    producer:
      bootstrap-servers: 'localhost:29092'
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: unittestexample-aluno
      auto-offset-reset: earliest


unittestexample:
  config:
    kafka:
      topics:
        unittestexample-aluno: 'unittestexample.aluno'

server:
  port: 8083
