name: Build and Run Testes Integrados

on: [pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout on repository
        uses: actions/checkout@v2
      - name: Configure Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Initialize Docker Infrastructure
        run: docker compose up --build -d
      - name: Run the cucumber test
        run:  mvn test -Dtest=TestRunner
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v5
        with:
          name: Relatorio-Cucumber
          path: target/cucumber-reports/cucumber.html