name: Build and Run Integ Tests

on: [pull_request]

jobs:
  build-and-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout on repository
        uses: actions/checkout@v2
      - name: Configure Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Build and run unit tests and
        run: mvn com.spotify.fmt:fmt-maven-plugin:format
      - name: Initialize Docker Infrastructure
        run: docker compose up --build -d

